TRUNCATE Customers;

INSERT INTO Customers VALUES
(1, 'Bamby', 'MacCorkell', 69, 'Portugal'),
(2, 'Manon', 'Kirkam', 79, 'Libya'),
(3, 'Osborne', 'Staley', 62, 'Mexico'),
(4, 'Keir', 'Arrington', 77, 'United States'),
(5, 'Aluino', 'Dewsnap', 62, 'China'),
(6, 'Oswald', 'Maskell', 28, 'Russia'),
(7, 'Desiri', 'Spinas', 63, 'Norway'),
(8, 'Mercy', 'Kneesha', 57, 'Pakistan'),
(9, 'Channa', 'Codling', 41, 'France'),
(10, 'Dyanna', 'Fouldes', 25, 'China'),
(11, 'Shaina', 'Verissimo', 56, 'Indonesia'),
(12, 'Griffie', 'Feldberg', 77, 'Ireland'),
(13, 'Madeleine', 'Bisatt', 67, 'Croatia'),
(14, 'Yasmeen', 'Cromwell', 67, 'Philippines'),
(15, 'Geralda', 'Sproston', 59, 'France'),
(16, 'Ariela', 'Charrington', 38, 'Russia'),
(17, 'Carver', 'Dykins', 36, 'China'),
(18, 'Tedda', 'Brizland', 16, 'Nigeria'),
(19, 'Janka', 'Strathe', 29, 'Angola'),
(20, 'Alis', 'Scully', 28, 'Honduras'),
(21, 'Rad', 'Ruddin', 68, 'Italy'),
(22, 'Talya', 'Alenichicov', 88, 'Japan'),
(23, 'Carlyn', 'Spare', 73, 'Brazil'),
(24, 'Iseabal', 'Mountford', 97, 'Thailand'),
(25, 'Tisha', 'Fitchen', 38, 'Palestinian Territory'),
(26, 'Mercy', 'Jeske', 95, 'Russia'),
(27, 'Evvy', 'Ambroise', 56, 'Malaysia'),
(28, 'Chrisy', 'Wildbore', 91, 'France'),
(29, 'Say', 'Baildon', 55, 'Hungary'),
(30, 'Budd', 'Fluck', 57, 'Chile'),
(31, 'Vaughn', 'Bottleson', 85, 'Jordan'),
(32, 'Gabriell', 'Rosenfarb', 79, 'Argentina'),
(33, 'Benedict', 'Benez', 63, 'China'),
(34, 'Malva', 'Fibben', 68, 'Philippines'),
(35, 'Harlan', 'Doumerc', 18, 'China'),
(36, 'Odo', 'Duerdin', 47, 'Portugal'),
(37, 'Codie', 'Amaya', 33, 'Brazil'),
(38, 'Rebecca', 'Reisen', 27, 'Dominican Republic'),
(39, 'Ronny', 'Mahood', 25, 'Botswana'),
(40, 'Eunice', 'Ambrosini', 27, 'Colombia'),
(41, 'Tuckie', 'Arne', 29, 'China'),
(42, 'Garth', 'Mertel', 97, 'Morocco'),
(43, 'Goddard', 'Stallebrass', 23, 'Peru'),
(44, 'Renaldo', 'Funcheon', 74, 'Poland'),
(45, 'Marget', 'Orred', 71, 'China'),
(46, 'Nissy', 'Chesterton', 36, 'China'),
(47, 'Laurens', 'Tallet', 52, 'Philippines'),
(48, 'Jordana', 'Nestoruk', 79, 'Indonesia'),
(49, 'Elberta', 'De Miranda', 72, 'Indonesia'),
(50, 'Nike', 'Dedenham', 50, 'Bosnia and Herzegovina'),
(51, 'Pepillo', 'MacNucator', 18, 'China'),
(52, 'Joeann', 'Kiddell', 75, 'Mexico'),
(53, 'Melany', 'Jozefowicz', 32, 'Indonesia'),
(54, 'Lorelei', 'Murrigans', 50, 'Palestinian Territory'),
(55, 'Claretta', 'Worsham', 10, 'Mozambique'),
(56, 'Bibbie', 'Spat', 29, 'Ukraine'),
(57, 'Yolande', 'Skett', 36, 'Vietnam'),
(58, 'Berkie', 'Bortolazzi', 45, 'Poland'),
(59, 'Jesus', 'Langmaid', 88, 'Guatemala'),
(60, 'Osbourn', 'Lightowlers', 92, 'Indonesia'),
(61, 'Mart', 'MacKeeg', 27, 'Philippines'),
(62, 'Bobby', 'Stranaghan', 93, 'Dominican Republic'),
(63, 'Phebe', 'Hansford', 79, 'Czech Republic'),
(64, 'Gifford', 'Parrington', 48, 'Sweden'),
(65, 'Brynna', 'Lafayette', 28, 'Brazil'),
(66, 'Camey', 'Latour', 97, 'France'),
(67, 'Olav', 'Wasiela', 43, 'Peru'),
(68, 'Gypsy', 'Hankin', 77, 'Malaysia'),
(69, 'Christos', 'Lavigne', 96, 'United States'),
(70, 'Janeta', 'Nanelli', 78, 'Japan'),
(71, 'Claudius', 'Saunderson', 50, 'Croatia'),
(72, 'Anissa', 'O''Deoran', 87, 'China'),
(73, 'Inigo', 'Schruyer', 42, 'Venezuela'),
(74, 'Conny', 'Lapree', 40, 'China'),
(75, 'Binky', 'D''Ambrogi', 34, 'Hungary'),
(76, 'Lucina', 'Waddilove', 25, 'Greece'),
(77, 'Sallee', 'Mathivat', 90, 'Ukraine'),
(78, 'Rosa', 'Fosdyke', 85, 'Honduras'),
(79, 'Raddie', 'Orrah', 31, 'China'),
(80, 'Mikel', 'Dreakin', 97, 'Sweden'),
(81, 'Brice', 'Been', 34, 'Syria'),
(82, 'Elane', 'Votier', 97, 'Philippines'),
(83, 'Towney', 'Campsall', 87, 'Indonesia'),
(84, 'Suzanna', 'Judd', 68, 'Angola'),
(85, 'Jodie', 'Hradsky', 87, 'China'),
(86, 'Hollyanne', 'Benois', 69, 'Indonesia'),
(87, 'Raimundo', 'Gregoriou', 20, 'Spain'),
(88, 'Jacinda', 'Swidenbank', 62, 'Peru'),
(89, 'Paco', 'Antonich', 97, 'Morocco'),
(90, 'Ode', 'Dryden', 42, 'China'),
(91, 'Ronna', 'Waylen', 27, 'Argentina'),
(92, 'Roselia', 'Dowdall', 54, 'Japan'),
(93, 'Francisco', 'Kytter', 95, 'China'),
(94, 'Tab', 'Hayne', 27, 'Poland'),
(95, 'Kylie', 'Kale', 49, 'Portugal'),
(96, 'Jessalyn', 'Castillon', 65, 'Gambia'),
(97, 'Abner', 'Noon', 58, 'United States'),
(98, 'Gare', 'Odgaard', 28, 'China'),
(99, 'Chrystel', 'Long', 59, 'Pakistan'),
(100, 'Asher', 'Kilmister', 27, 'Indonesia');

SELECT * FROM Customers;